language: minimal

install:
  # Install GraalVM with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 20.2.0.r11-grl

  # Check if GraalVM was installed successfully
  - java -version

  # Install Maven, that uses GraalVM for later builds
  - sdk install maven

  # Show Maven using GraalVM JDK
  - mvn --version

  # Install GraalVM Native Image
  - gu install native-image

  # Check if Native Image was installed properly
  - native-image --version
script: bash server/redeploy.sh
env:
  global:
    - myname=joejoejoe
    - secure: "hy99v9pu7k3S0g+nb2YF/48NHaLzrKor24s6TV0Vaynnti0TiywHDxBE3SpfCyCad6klihguyTOnkhQCuFN8BbqphrS4YT6EjkEOqi0R8O4VLJcV8L8RNTiaW0chig3MqmNMNMtv6PuTxyjmRsX6gL66VN2qT1cYky6He+IIoBLIPbtY1jH9F7GEGS/zvvriwVuCQ1QXuXiSfb1Dd2TWFMabTVyVqENLgui7bvZxIFFKjFG7eQZlCLntC2X5HPwFQOMSa4YoswouapNxjjIHmX4uCLRJVKfbWDcNF/B8E5Y35jTxRZOu6WgilEk/g/I3D38U8C+8FMlEOPaVolN49CilUZd6Iz6p0Sy6te9gLRM2kBomCpDYXb0ntjMe2zyelbYQ4CT3tfNrseClUN68M9mt0hmqZfJ/D0MdG7c5yK2C7t2HCmi+ylur8zwPxT40JkuVWmB9atKoe6HGOEr8oZnnXLrLBhCv5H36UxRFsE2wXCTesdq8oxjtnWNxDuNLntMg4vYke3u+DNcfIPntKZ6hoyzgDhpnBAevaDgRAinwAs+Q22qF+KkbK/zBOPHwgpDehWgMhALYvASll3kPjZ5L1EjsMcHpBBKAdL3gWpUvlG9T6TKEYoRCNhg441ZwWO0HvA1/+ImX2ojXHuJ6T9Jf2B9hIcsg5qsbao+pTW4="
  jobs:
    - myname=gagaga
    - secure: "FgmiqC6nyO70nJPOTMQPrQIoMOpXy3VzRkpQ6gfZoJ+yTchk55cMwKPNekAbwEd1pTlRWO9ikW0w1N3VBujliiVoo00nKfAq0U7a7b1aoq+gOf6v0qdH/WpYW8X41hdQVFwfg32qd9mD3w1p07Ke9iZ76JJDH6t9FHWNlWuNzl+QoXwnoZfncl+o2za69t1rTEoqOY4UyawnfAoMxUgMFUZ+tNCxFaYEX8PWFm3nuk38cO8ZKhVf67cIKc+Ff8ejj657iDYecEU2q1gx1bpijEsbReD1I3jB9Q5K9omCI9MjzNIfyWNgB9wZo4vt7Un0dBnS3lpFtBDNeaVuIkAHShnMpcGIBz3Vil93djC9HVRUN79fvtzcCAfRQEDiTZ/H1WMRRg7qXf3VO1M/fNjyEPyAKKnsdAdzudTxVDtAgw8eIaGTEiCQlUcGWsGpwH8uCD+423Vv5kbgqECwDV9ICbFI3llb6JVrSlUPuc1wOkHgOlkmp2X9BfKFxzWj3vA66xqhyIVsSpvQwVYXb2wxKdF41VbI9fIsX06tSCOWQb374spLuzJy8mnHPiKMm5et5YxMZsJ83jOzelN9+u99VHHajrpcTGtRkAyrWllJZFpgAna4a+HrD9wEHqszuM2EbMg9br2uBGh924nWJI+VYia/FBGGAcGWv9L9x7+AwBg="
