language: minimal

addons:
  ssh_known_hosts:
    - sh.asdk.io

env:
  global:
    - SERVER_HOST=sh.asdk.io
    - secure: d7GGGSjoXYiGmxOqbxq+uFzHz3T7/r17nPahcvvz1weAzeSP1pbEzCiXoyR1+ZcOMZStgcprfVO6aDwajptXv0gj9o4bCp61QCzMkAHLgMvhB2ZtRZ424IQzPbJtSSCloFJbQ1Xwr1kApUj6RPiIAZqKFBNxIfk0jeUDLiYq66lZ4t04oUQ7r63RbB4NBTZBBHsrA7NxYHettqnHQlFZ5eWAYfTbycRWds74o5SXNHsCpIE397TYj/efIj3h1ZqR4NHGI5teH2hShCdTbPrksRiMxWurmc0mpS/OTk2InDpb0fZe9NKey3eqcxib0aEBs2/1XqSr0WjEH7t5VMWwHm6FakPnvtMG/OBOx2xbwaXgAnRrBpqG5TtMWNkFscihbKhEZB8vYVlabEKoIToD7iJRdF43nb9WNPl0PrhsZY4yOwu5BCl3LxCD/MbQrunJR7S8NRPEuOhyvbKuscjUormvjzuiDA+14Nr2nXJS1/ZD7qNycuOx52DWUvwvR3O47M5b4Wxo3kxwRiImcDs+I3rF08/PT369+12RirRO5pwCu26mtUKvo5fxbkmEzlygRxUHvTNPHKZtfsXfHEiIkS7Z4PrYkhajpIU2GogcJInDedKuHGSC53cHZIyJno1llmmhyKa3VZ7CDWkyDdnzTSgMd1lcbF1loDHBon/Cfu0=

before_install:
  - openssl aes-256-cbc -K $encrypted_6ffa3714fb6c_key -iv $encrypted_6ffa3714fb6c_iv
    -in travis_rsa.enc -out ./travis_rsa -d
  - eval "$(ssh-agent -s)"
  - pwd;ls
  - chmod 600 ./travis_rsa
  - echo -e "Host $SERVER_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./travis_rsa
  - ssh -i ./travis_rsa root@$SERVER_HOST pwd;ls

install:
#  # Install GraalVM with SDKMAN
#  - curl -s "https://get.sdkman.io" | bash
#  - source "$HOME/.sdkman/bin/sdkman-init.sh"
#  - sdk install java 20.2.0.r11-grl
#  # Check if GraalVM was installed successfully
#  - java -version
#  # Install GraalVM Native Image
#  - gu install native-image
#  # Check if Native Image was installed properly
#  - native-image --version
#  # build the quarkus app
  - cd server
#  - ./mvnw -version
#  - ./mvnw package -Pnative

script:
#  - bash redeploy.sh
