language: minimal

install:
  # Install GraalVM with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 20.2.0.r11-grl

  # Check if GraalVM was installed successfully
  - java -version

  # Install Maven, that uses GraalVM for later builds
  - sdk install maven

  # Show Maven using GraalVM JDK
  - mvn --version

  # Install GraalVM Native Image
  - gu install native-image

  # Check if Native Image was installed properly
  - native-image --version

script: bash server/redeploy.sh

env:
  global:
    - GVAR=GLOBALVAR
    - secure: "s0CJSHWCjFfTizzQWCILL/75bVm6wqJUfJ6cWwRrG+kHqYEOC/b5KP5XLs7eEiWsMb6CdEm+YUdmNFXkODZhFXd04mQ3/097v+/eoqhMW+R+IPlHGqmrnDCkdydOfam2vK35ZCuZpL7Wd08k7OE7m2SQoTmJVheLUy2GbPsMnVECzlFkm2Rh49XZ+8VPxdiv/27LpOWj/uLW0QrtHHsIw3JcRhqMlSwRlSsm9CF/psdpzqmfi01iFso6sRBvIpBT4LoBpmwmo9Ybr5MnRNSvWf44Hk6YIJXuxl0wtJIz9Od9Y2VTwXJBbVzi7ScusRpV+pPyIQ37NCEQgpegBPsw7XGiiO+hhKXw7m4Mx1hjaqYU0t5DJ2g2EsjsgxGWxv7g2iJLg7YMw4Xf6oR01A/WE5tbdJcHznsyg6oeytQtkwMEI+UZnI7Ngw/1BiZ4ExdnkkQwL/WY4HXJdvWy/Ek05HprrHyKeeBx7Bv45Bcgu9h4nCKtaxRqCvsMwFOduI60My4zkKrxpUnH6ryKRvjuDRu4HuwWcRHQwxjNMoXaP64xq5scyNsjy5LGOnj/4EyVATcUwtWHWtp6YJTfxNyvRJTdIE4VXjQazhr75qd5SB08tzcby3NHF2yDTtKpxMr8crjEon5s1DrACOXIq2tMiwEQ7PsfUatz87sk1CKhbcE="
  jobs:
    - JVAR=JOBVAR
    - secure: "nBZCUspSItRnfVNM+cYTYaZxvBjDzLHAMLc+hr2ttjXiE5UuHLUbohwhXel1XhtgZ4frMusp0i2wwPC6nEJBTCrMwMHqApxa7Hq2loyaZTkASOq4xQoYrDvMG115c4+zrT4q9q7rdX7zUKveLc3zL+eEuRRNVvuN40hDyxdNNUQgXc5fSirvHwltpNMI0W810BW/VTK5+zrpG6ORMdpylfZJHcAzLcXC3nEYyKYEf3Ady5l/VJAzH4XjXBN3puWjRdiHhfRWLkuqa1SiOAPjvNN6iXhex3Cpmyzh+NSqq/ahzYtIQy9qAZ7udtbEq6RkkLimp2Dw6B9FBeAYNNI7TfBj8GzFqt3zrBbkqxdg+R5oQWuIYu9X+KrCIRLrB10piX8DPAInkGD5FYhAMTh+W8hG/gz4is8WDQNATQeWV5aANP2rJkkkUt73Nv7zIGc5B8R+HaSFer8/yZAef5cweUY/gW5PjdrjwUOLzmaW5XFK3H4+6Sq7DQ4rjdstIo07uV15trbhSSY82WWpl7MS0AElVjyLUPgLJOGid+hMHcWpC/rZMraqRFmgVpmEjUPJFgTZ/meZm2PKW4/A+/Eaz6xrNVsVLuWmkPSSRpZ/c8eJwlKunCpQnI+OzK0QRIp8fvYNAvFaXPiWaXAz1EZyAGNWEwga35tYdjj/jvPHYpQ="
