language: minimal

install:
  # Install GraalVM with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
#  - source "$HOME/.sdkman/bin/sdkman-init.sh"
#  - sdk install java 20.2.0.r11-grl
#
#  # Check if GraalVM was installed successfully
#  - java -version
#
#  # Install Maven, that uses GraalVM for later builds
#  - sdk install maven
#
#  # Show Maven using GraalVM JDK
#  - mvn --version
#
#  # Install GraalVM Native Image
#  - gu install native-image
#
#  # Check if Native Image was installed properly
#  - native-image --version

script: bash server/redeploy.sh

env:
  global:
      secure: pyf7bl7PG4mVfyWzQ5tuNDyxS570SPRIZHi8Xkqy4KDbFPjLNx33LdFRgRLLHHWMxvbVJOwsAQYpFdHFwFldVVTIjqTQk8h/Z5+7KLCvoAPcZ0ow9jY7b8HQmvXSd0tfYOqNcTQ/XhKuf5HgftxC0ZSIx1vvoGEVRBm+Nl2+wjpy0ilPvFy3vMV/oWXBt3OrUmxFsQtWvDVgjOo5thD0y69oKSdxJrptgMYGB+MkB5omMTRr+iU2p+0E//EGbAs6iaO98jdTdrqqCR3hzmeud9Yp6djZQxgFNcx5MpxrEb5KixUNJxth2EOEmKP/RqDWUn7VrcaPMYYocegrfx8guWtVQsiLGD1WeAfArwqHwe4zQ6BbLgO/VtqbYJVPM+4POExO0GIJo9StKZ/mstw/KoFK8nUavvD6yJi8Ta3uz8wKO8O7N+ufG6qNKqZUNoWaDjU/uYQHPtPLvzMXqMa+/IcOTRgQzsO6eP3E86c3E1laSOW38zdXUzYClayXXR2yo2Ns3p1Dp0wsGVaf2IVn+Jcs2y8c1bHlSBUotE+gQDg6rkpNqM/hwLBnWnp7lB955g5ne+3sFXLbaql+69eiHXPuDHtjFFwZd9TnIEWZUz1C+ktb4rBHzE3jPoFVwH20tWc5x5Ki/F5tiecu85fryy1/wXuVPrr5v5j9tX825hg=
  jobs:
      secure: HZOwfG+j1kuvSSUHesuJNCG8kphtIiTesxYpZ4dX4hcIHYVYYWn++AaNPdA6zIZrt2gtpPOexR2C9sDFHjUBLm5NxmZ9WobhtNEBJCr7bHRM0W6jRhvCmNMm69RADSob5GsbK7jwkIs90P8RG319P1c01iZ8po0Wgzz9kRHLWojuQCSI+d/HgATLhh/lXQJuKHwQseP+z+bvbF5uAuVADLCdZdodNhkoO5Cjyq2/g5ovWXMu7+DHhd3pIfW6V7TQOGEtMtHPbVIaSB3WfWjQ+7HH3vMrBsa+rplL6L9LIz5E+fOi2Q/9zfJstqvIbatzicG8tROTg/8IyrxnWO9W4FA6Gag5JttOTmEzULNWMYWB3bkZP8Wkx0PgL1Gx7Tp7iFxQoyj3X0L0qIAKnPc6+H6imUvtU7jQ0CZRh971T4APHHXpk8SDC642xXcdmjFaBQrBOD4GB0OjBa4uHiLh65WpZTkzsHcBp3DvjPjWurH3NZOndIkWECaDN2B+pnEcUNXLkTNsGEIFXYEhYAhTme18nNMAFEY7JBLieWXM3EFAdQXPmXTbfHELbCQdqNqD+sdfXT3wY94v4qOkaaxvcsW3tdfYtbdlupOvinPBgx5eRLfGQ4hy79Aqf4RJEFOD9uKfXrbx82sOyzWr4JDI9GNhkvcURlK12KzdS83xdmA=
