language: minimal

install:
  # Install GraalVM with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
#  - source "$HOME/.sdkman/bin/sdkman-init.sh"
#  - sdk install java 20.2.0.r11-grl
#
#  # Check if GraalVM was installed successfully
#  - java -version
#
#  # Install Maven, that uses GraalVM for later builds
#  - sdk install maven
#
#  # Show Maven using GraalVM JDK
#  - mvn --version
#
#  # Install GraalVM Native Image
#  - gu install native-image
#
#  # Check if Native Image was installed properly
#  - native-image --version

script: bash server/redeploy.sh

env:
  global:
      secure: og6HDJ3Xi55feUG9bDfj5Bz4da9harc9dSn8dObmuQGINuLQqpngY6QDlHIVJ2J4CmUsG/bW+1Ux7CJsmxar5Wj1rCIyAs/sIz3s0hIAxx84ZCmEDpRgPuNxMPJ6Ra/doMR2+2eQUfJ4KeQm4JRE+Lbu+nyuzHzFnQpiXcYbSaKU8uF0dMQX5yL7pyVLcENBii8PWBEXNmjDEWd32R9/OHAMOWVRvQwuda3kCnKZ4lUzdCee6R8tsPpJJTsryU2Z3LVIjIGgX+fvsjES/gCdjo5kmut4DOGRfwrzhvPeOQ1oVWOSCy+EttRt4um/CQ6wSGLp9s33j25gR6p/7qtARw8XaSeiThdOMBMr4R00yhETEWO8dhWaF3Rs17H0OiDf9kaJtoNAQKm5ZFPBnltMc8GuoUePsA0JQ8li2EZ55cem7v6BWmCGueo8GOdoTg3bK7HjpPYeQdOpOC8Vo/gzJsI+sKCr1KOBcB91gXgJqHAVfRpYlzWdlu5c0er8ycKIR8icIdTFIOjonnfVcHAfzpA4cLuhhu1igx2zJ7M/8f+bsx6lMAqIByTh6M5cvZmN4+arqNK23sYlfEoVxJ8jR0tmZ83xli1HlcHf0GTR0QZ9okl3wPa+eFSZx+wRST50BqoZy/W9OHqjuE6ySI7IPzaIEDFfWS9F1uJiSMWK/xo=
  jobs:
      secure: HZOwfG+j1kuvSSUHesuJNCG8kphtIiTesxYpZ4dX4hcIHYVYYWn++AaNPdA6zIZrt2gtpPOexR2C9sDFHjUBLm5NxmZ9WobhtNEBJCr7bHRM0W6jRhvCmNMm69RADSob5GsbK7jwkIs90P8RG319P1c01iZ8po0Wgzz9kRHLWojuQCSI+d/HgATLhh/lXQJuKHwQseP+z+bvbF5uAuVADLCdZdodNhkoO5Cjyq2/g5ovWXMu7+DHhd3pIfW6V7TQOGEtMtHPbVIaSB3WfWjQ+7HH3vMrBsa+rplL6L9LIz5E+fOi2Q/9zfJstqvIbatzicG8tROTg/8IyrxnWO9W4FA6Gag5JttOTmEzULNWMYWB3bkZP8Wkx0PgL1Gx7Tp7iFxQoyj3X0L0qIAKnPc6+H6imUvtU7jQ0CZRh971T4APHHXpk8SDC642xXcdmjFaBQrBOD4GB0OjBa4uHiLh65WpZTkzsHcBp3DvjPjWurH3NZOndIkWECaDN2B+pnEcUNXLkTNsGEIFXYEhYAhTme18nNMAFEY7JBLieWXM3EFAdQXPmXTbfHELbCQdqNqD+sdfXT3wY94v4qOkaaxvcsW3tdfYtbdlupOvinPBgx5eRLfGQ4hy79Aqf4RJEFOD9uKfXrbx82sOyzWr4JDI9GNhkvcURlK12KzdS83xdmA=
