language: minimal

install:
  # Install GraalVM with SDKMAN
  - curl -s "https://get.sdkman.io" | bash
#  - source "$HOME/.sdkman/bin/sdkman-init.sh"
#  - sdk install java 20.2.0.r11-grl
#
#  # Check if GraalVM was installed successfully
#  - java -version
#
#  # Install Maven, that uses GraalVM for later builds
#  - sdk install maven
#
#  # Show Maven using GraalVM JDK
#  - mvn --version
#
#  # Install GraalVM Native Image
#  - gu install native-image
#
#  # Check if Native Image was installed properly
#  - native-image --version

script: bash server/redeploy.sh

env:
  global:
      secure: Wlb8Vd/DDQXsY4mAvMpb6r5rs3POsiGRPHVOuSFYeSijQrMEE817c4ueieoRn59vd9BetDAdxyAmjmuGeTB2MstTule+lfRBhudzpRsFJ6BD8Pf3XLiwVnaHZGVNKL1IbPFyOm2BWj7ZL2S7UWJ8XpYRd+knfztX4u1Jf9mAuN7XO0HmleriFYw1IFY1OmQwJBXIWm0EAmaQl/32zpO9g9nq6uo3lAXhg7kq0vbDbANDAnQhh1i5ICkeGB+Ibb3Wna/7aFXJUtogRF/wmxRQDSn1sQi3kReZaH8p1lVCjKFGF2CR2ho7i7ry7P64xLOAYsIB40dSiJpZjooQmQI3PnBbeaJbgk3FBrG0+Z5imAA66Bwi5xKIrXMZDa1URHzCGVWk5Jts/TiMdDKzZrnoyPt+oWAnRtI+ksgVhOKq8wNgDvE5xZClKl1z9BRotVFTXUI3IphJ2ZchnBRQJ1+d1TlFtnwCBsOGZ16rsxUx7ygaMa2gAMJu98vjnDn6VBvYg5QCMpiZ2NyQxOse/EoSOluruMriyvugRkNJYOscMa8umrrXg522MSoA35ufsj0Es5+VedFsgyWV+QHVju5LSBk4KAwPn3hFMFJYpDlOAWqLncQlfNYB6YMehMst57YSzhRYs7S3eV5WhvKTfCTxxjS+VfUBUiOcTYDnLrmU1Nw=
  jobs:
      secure: Wlb8Vd/DDQXsY4mAvMpb6r5rs3POsiGRPHVOuSFYeSijQrMEE817c4ueieoRn59vd9BetDAdxyAmjmuGeTB2MstTule+lfRBhudzpRsFJ6BD8Pf3XLiwVnaHZGVNKL1IbPFyOm2BWj7ZL2S7UWJ8XpYRd+knfztX4u1Jf9mAuN7XO0HmleriFYw1IFY1OmQwJBXIWm0EAmaQl/32zpO9g9nq6uo3lAXhg7kq0vbDbANDAnQhh1i5ICkeGB+Ibb3Wna/7aFXJUtogRF/wmxRQDSn1sQi3kReZaH8p1lVCjKFGF2CR2ho7i7ry7P64xLOAYsIB40dSiJpZjooQmQI3PnBbeaJbgk3FBrG0+Z5imAA66Bwi5xKIrXMZDa1URHzCGVWk5Jts/TiMdDKzZrnoyPt+oWAnRtI+ksgVhOKq8wNgDvE5xZClKl1z9BRotVFTXUI3IphJ2ZchnBRQJ1+d1TlFtnwCBsOGZ16rsxUx7ygaMa2gAMJu98vjnDn6VBvYg5QCMpiZ2NyQxOse/EoSOluruMriyvugRkNJYOscMa8umrrXg522MSoA35ufsj0Es5+VedFsgyWV+QHVju5LSBk4KAwPn3hFMFJYpDlOAWqLncQlfNYB6YMehMst57YSzhRYs7S3eV5WhvKTfCTxxjS+VfUBUiOcTYDnLrmU1Nw=
